# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'my-maths-service' }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        
      - name: Build project source and run unit tests
        shell: bash
        run: |
          dotnet restore "MathsServiceWithUnitTest.sln"
          dotnet build --no-restore
          cd MathsServiceUnitTest
          dotnet test --no-build -v=normal
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      # Build Docker image
      - name: Docker build
        run: | 
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          
    # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          cd ./Maths-Service
          docker build -t maths-service -f Dockerfile .
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
